Firefly/Controllers/CategoryController.cs
using Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Firefly.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
           
            return View();
        }

        [ChildActionOnly]
        public ActionResult MainMenu()
        {
            var model = new NewsCategories().GetCategory();
            return PartialView(model);
        }

        public ActionResult Category(int cateId)
        {
            var newArticles = new NewsArticles();
            ViewBag.NewsArticles1 = newArticles.ListNewsArticle1(1);
            ViewBag.NewsArticles6 = newArticles.ListNewsArticle6(1);
            ViewBag.NewsArticles2 = newArticles.ListNewsArticle2(5);
            ViewBag.NewsArticles3 = newArticles.ListNewsArticle3(1);
            ViewBag.NewsArticles4 = newArticles.ListNewsArticle4(5);
            ViewBag.NewsArticles5 = newArticles.ListNewsArticle5(7);

            var category = new NewsCategories().ViewDetail(cateId);
            return View(category);
        }
        public ActionResult Detail(int id)
        {
            var article = new NewsArticles().ViewDetail(id);
            //ViewBag.NewsCategory = new NewsCategories().ViewDetail(article.CategoryID);
            return View(article);
        }
    }
}

Firefly/Views/Shared/Footer.cshtml
@model Model.EF.Footer

@Html.Raw(Model.Content)

Firefly/Views/Shared/FooterMenu.cshtml
@model  List<Model.EF.NewsCategory>

<section class="buttom-footer py-lg-5 py-md-4 py-sm-3 py-3">
    <div class="headder-logo-icon text-center">
        <span class="fab fa-accusoft"></span>
        <h2 class="mb-3"><a href="/Home/Index">Firefly</a></h2>
    </div>
    <div class="buttom-nav py-3">
        <nav class="border-line">
            <ul class="nav justify-content-center">

                @foreach (var item in Model)
                {
                    var url = "/danh-muc/" + @item.MetaTitle + "-" + @item.id;
                    <li class="nav-item">
                        <a class="nav-link" href="@url">@item.name<span class="sr-only">(current)</span></a>
                    </li>
                }
                @*<li class="nav-item active">
                    <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a href="about.html" class="nav-link ">About</a>
                </li>
                <li class="nav-item">
                    <a href="service.html" class="nav-link">Services</a>
                </li>
                <li class="nav-item">
                    <a href="contact.html" class="nav-link">Contact</a>
                </li>*@
            </ul>
        </nav>
    </div>
</section>

Firefly/Views/Shared/MainMenu.cshtml
@model List<Model.EF.NewsCategory>
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="col-lg-1">
      
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="icons">
        <ul>
            <li><a href="/Home/Index"><span class="fab fa-accusoft" style="width:100px !important">Firefly</span></a></li>
        </ul>
    </div>
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      
        <ul class="navbar-nav ">
            @foreach (var item in Model)
            {
                var url = "/danh-muc/" + @item.MetaTitle + "-" + @item.id;
                <li class="nav-item">
                    <a class="nav-link" href="@url">@item.name<span class="sr-only">(current)</span></a>
                </li>
            }

            @*<li class="nav-item">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a href="about.html" class="nav-link">About</a>
            </li>
            <li class="nav-item">
                <a href="service.html" class="nav-link">Service</a>
            </li>*@
            @*<li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pages
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="nav-link" href="errorpage.html">404 Page</a>
                    <a class="nav-link " href="typography.html">Typography</a>
                    <a class="nav-link " href="blog.html">Blog</a>
                    <a class="nav-link " href="blog_one.html">Blog-1</a>
                </div>
            </li>*@
            @*<li class="nav-item ">
                <a href="contact.html" class="nav-link">Contact</a>
            </li>*@
        </ul>
    </div>
</nav>

Firefly/Views/Shared/_Layout.cshtml
<!--A Design by W3layouts
   Author: W3layout
   Author URL: http://w3layouts.com
   License: Creative Commons Attribution 3.0 Unported
   License URL: http://creativecommons.org/licenses/by/3.0/
   -->
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Inside-Art a Blogging Category Bootstrap responsive Website Template| Single Page :: w3layouts</title>
    <!--meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Inside-Art Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
         Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!--//meta tags ends here-->
    <!--booststrap-->
    <link href="/assets/client/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <!-- font-awesome icons -->
    <link href="/assets/client/css/fontawesome-all.min.css" rel="stylesheet" type="text/css" media="all">
    <!-- //font-awesome icons -->
    <!--stylesheets-->
    <link href="/assets/client/css/style.css" rel='stylesheet' type='text/css' media="all">
    <!--//stylesheets-->
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
</head>
<body>
    <!--headder-->
    <div class="header-outs" id="header">
        <div class="headder-nav-icon">
            <!--//navigation section -->
                @{Html.RenderAction("MainMenu", "Category", "Home"); }
        </div>
        @RenderSection("headder_index", required: false)

    </div>
    <div class="main">
        @RenderBody()
    </div>
    <!--Footer -->
    @{Html.RenderAction("FooterMenu", "Home"); }
    <footer>
        @{Html.RenderAction("Footer", "Home"); }
    </footer>
    <!-- //Footer -->
    <!--js working-->
    <script src='/assets/client/js/jquery-2.2.3.min.js'></script>
    <!--//js working-->
    <!-- start-smoth-scrolling -->
    <script src="/assets/client/js/move-top.js"></script>
    <script src="/assets/client/js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
    <!-- here stars scrolling icon -->
    <script>
        $(document).ready(function () {

            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };


            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <!-- //here ends scrolling icon -->
    <!--bootstrap working-->
    <script src="/assets/client/js/bootstrap.min.js"></script>
    <!-- //bootstrap working-->
</body>
</html>